collections:
  training:
    output: true
    permalink: /training/:name/
  trainers_hub:
    output: true
    permalink: /trainers_hub/:name/
  events:
    output: true
    permalink: /events/:name/
  incentives:
    output: true
    permalink: /incentives/:name/
